spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-micro-user
    username: postgres
    password: Pawan@123

  jpa:
    hibernate:
      ddl-auto: update

  database-platform: org.hibernate.dialect.PostgreSqlDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8081